#!/usr/bin/env python3
"""Bundle the dashboard into apps-script/Index.html for Google Apps Script.

Apps Script serves a single HTML file, so this inlines the stylesheet, the
shared display scripts and the garden image, drops the GitHub-only data files,
and adds apps-script/loader.js, which reads the numbers from the Google Sheet.

Run after any design change:  python3 tools/build_apps_script.py
"""
import base64
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHARED_SCRIPTS = ["common.js", "tabs.js", "icons.js", "agriculture.js", "script.js"]
GITHUB_ONLY = ["vegetables.js", "data.js", "gardeners.js", "main.js"]


def read(name):
    return (ROOT / name).read_text(encoding="utf-8")


def replace_once(html, pattern, replacement, what):
    new, count = re.subn(pattern, lambda _: replacement, html, count=1)
    if count != 1:
        sys.exit(f"build failed: could not find {what} in index.html")
    return new


def main():
    html = read("index.html")

    html = replace_once(html, r'<link rel="stylesheet" href="styles\.css[^"]*">',
                        f"<style>\n{read('styles.css')}\n</style>", "the stylesheet link")

    svg = base64.b64encode((ROOT / "assets/garden.svg").read_bytes()).decode()
    html = replace_once(html, r'src="assets/garden\.svg"',
                        f'src="data:image/svg+xml;base64,{svg}"', "the garden image")

    for name in GITHUB_ONLY:
        html = replace_once(html, rf'[ \t]*<script src="{re.escape(name)}[^"]*"></script>\n',
                            "", f"the {name} script tag")
    html = re.sub(r"[ \t]*<!-- Data \(GitHub version only.*?-->\n", "", html)

    for name in SHARED_SCRIPTS:
        html = replace_once(html, rf'<script src="{re.escape(name)}[^"]*"></script>',
                            f"<script>\n{read(name)}</script>", f"the {name} script tag")

    html = replace_once(html, r"</body>",
                        f"  <script>\n{read('apps-script/loader.js')}</script>\n</body>", "</body>")

    header = ("<!-- GENERATED by tools/build_apps_script.py from index.html, styles.css and "
              "the shared scripts. Do not edit by hand: change those files and rebuild. -->\n")
    out = ROOT / "apps-script/Index.html"
    out.write_text(header + html, encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
